### ISSUE TITLE
您好，我对您的研究很感兴趣，我出现了这个错误，请问如何解决，谢谢IndexError: list index out of range

### ISSUE THREAD

**Issue by Yuehongzhe** [Pointcept/OpenIns3D#17] opened 2024-08-29 13:28 UTC
python openins3d/main.py --dataset scannet --task OVOR --detector odise
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The checkpoint state_dict contains keys that are not used by the model:
  model_ema.{decay, num_updates}
  cond_stage_model.transformer.text_model.embeddings.position_ids
WARNING:fvcore.common.checkpoint:Keys with prefix are removed from state_dict:
backbone.feature_extractor.,category_head.clip.clip.,clip_head.clip.clip.
WARNING:fvcore.common.checkpoint:Removed 2482 ignored_state_dict keys from missing_keys
Total number of scenes in the scannet dataset: 312
  0%|                                                   | 0/312 [00:00<?, ?it/s]Processing scene scene0011_00
  0%|                                                   | 0/312 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/media/Disk/OpenIns3D-main/openins3d/main.py", line 270, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/media/Disk/OpenIns3D-main/openins3d/main.py", line 51, in __init__
    self.OV_object_recognition()
  File "/media/Disk/OpenIns3D-main/openins3d/main.py", line 184, in OV_object_recognition
    mask_classfication, score = self.lookup.lookup_pipelie(pcd_rgb, mask_list, scene, threshold = 0.5, use_2d = self.use_2d)
  File "/media/Disk/OpenIns3D-main/openins3d/lookup.py", line 277, in lookup_pipelie
    mask, label = self.ODISE.build_lookup_dict(scene_id, save = True)
  File "/media/Disk/OpenIns3D-main/openins3d/build_lookup_odise.py", line 112, in build_lookup_dict
    width, heigh = get_image_resolution(glob.glob(f"{self.Snap_path}/{scene}/image/*")[0])
IndexError: list index out of range

**Comment by ZheningHuang** [comment] 2024-08-29 14:29
Hi, thanks for your interests.


I suggest checking if the path for Snap images `{self.Snap_path}/{scene}/image/*`  is correct. The image might not have been read because the path seems to be set incorrectly.

**Comment by Yuehongzhe** [comment] 2024-08-30 10:35
(openin3d1) wsco2@vm-4090-2:/media/Disk/chengxu/OpenIns3D-main$ python openins3d/main.py --dataset scannet --task OVIS --detector odise
当前工作目录: /media/Disk/chengxu/OpenIns3D-main
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/home/wsco2/anaconda3/envs/openin3d1/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The checkpoint state_dict contains keys that are not used by the model:
  model_ema.{decay, num_updates}
WARNING:fvcore.common.checkpoint:Keys with prefix are removed from state_dict:
backbone.feature_extractor.,category_head.clip.clip.,clip_head.clip.clip.
WARNING:fvcore.common.checkpoint:Removed 2483 ignored_state_dict keys from missing_keys
Snap_path: output/snap
Total number of scenes in the scannet dataset: 312
  0%|                                                   | 0/312 [00:00<?, ?it/s]Scene scene0011_00 is already processed
*****************Start to render snap images for scene0011_00_vis*****************
  0%|▏                                        | 1/312 [00:14<1:17:44, 15.00s/it]Processing scene scene0011_01
*****************Start to render snap images for scene0011_01*****************
Snap module: 23 out of 24 images renderedWarning: mask is not properly formatted or is missing data.
检索到的图像文件列表: []
  0%|▏                                        | 1/312 [00:25<2:12:48, 25.62s/it]
Traceback (most recent call last):
  File "/media/Disk/chengxu/OpenIns3D-main/openins3d/main.py", line 270, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/media/Disk/chengxu/OpenIns3D-main/openins3d/main.py", line 49, in __init__
    self.OV_instance_seg()
  File "/media/Disk/chengxu/OpenIns3D-main/openins3d/main.py", line 86, in OV_instance_seg
    mask_classfication, score = self.lookup.lookup_pipelie(pcd_rgb, mask_list, scene, threshold = 0.3, use_2d = self.use_2d)
  File "/media/Disk/chengxu/OpenIns3D-main/openins3d/lookup.py", line 277, in lookup_pipelie
    mask, label = self.ODISE.build_lookup_dict(scene_id, save = True)
  File "/media/Disk/chengxu/OpenIns3D-main/openins3d/build_lookup_odise.py", line 120, in build_lookup_dict
    raise ValueError(f"未找到图像文件。请检查路径: {self.Snap_path}/{scene}/image/")
ValueError: 未找到图像文件。请检查路径: output/snap/scene0011_01/image/  请问这个是不是因为我内存不够还是，什么原因，24GB的虚拟机，应该不到24GB。如果是内存，请问有解决办法吗。还是是其他问题

**Comment by ZheningHuang** [comment] 2024-08-30 14:40
这个应该不是内存的问题， 

“请检查路径: output/snap/scene0011_01/image/” 

这里里面应该是有图片的，但是你的好像没有？

**Comment by ZheningHuang** [comment] 2024-09-02 00:26
你好，重新测试之后发现是加可视化的时候引入的一个小bug，详情请看 #19 。

感谢汇报，如果有后续问题请联系。

**Comment by JiachengDeng** [comment] 2024-09-05 02:55
What a coincidence! I encountered exactly the same bug, and even after fixing bug #19 , it still hasn't been resolved.

`(openins3d) djc@bj-3090:~/open-vocabulary/OpenIns3D$ python openins3d/main.py --dataset scannet --task OVOR --detector odise --save_vis False
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The checkpoint state_dict contains keys that are not used by the model:
  model_ema.{decay, num_updates}
WARNING:fvcore.common.checkpoint:Keys with prefix are removed from state_dict:
backbone.feature_extractor.,category_head.clip.clip.,clip_head.clip.clip.
WARNING:fvcore.common.checkpoint:Removed 2483 ignored_state_dict keys from missing_keys
Total number of scenes in the scannet dataset: 303
  0%|                                                                                                                                                                                                                                                                                                  | 0/303 [00:00<?, ?it/s]Processing scene scene0011_00
  0%|                                                                                                                                                                                                                                                                                                  | 0/303 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 281, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 51, in __init__
    self.OV_object_recognition()
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 195, in OV_object_recognition
    mask_classfication, score = self.lookup.lookup_pipelie(pcd_rgb, mask_list, scene, threshold = 0.5, use_2d = self.use_2d)
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/lookup.py", line 277, in lookup_pipelie
    mask, label = self.ODISE.build_lookup_dict(scene_id, save = True)
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/build_lookup_odise.py", line 112, in build_lookup_dict
    width, heigh = get_image_resolution(glob.glob(f"{self.Snap_path}/{scene}/image/*")[0])
IndexError: list index out of range`

**Comment by ZheningHuang** [comment] 2024-09-05 08:03
Thanks for reporting I will get this fixed tonight.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZheningHuang** [comment] 2024-09-06 13:49
Hi Jiacheng,
I was wondering if you're using the latest version of OpenIns3D when encountering this issue. I just tested it on my side and it worked without any problems. I know this was a problem in a previous version, but it should be fully resolved in the newer release.
If you manually updated via [this link](https://github.com/Pointcept/OpenIns3D/issues/19), that might not be sufficient to resolve the issue. Please pull from the main branch to ensure you have the latest fixes.
Let me know how it goes!

**Comment by JiachengDeng** [comment] 2024-09-08 03:38
Hello Zhening,

First of all, I apologize for the delayed response and keeping you waiting. I have successfully started training the scannet OVIS with the newer release, but over the past few days, I’ve been working hard to fix some other minor bugs I encountered. For example, I’m currently addressing the following issue: 

`Processing scene scene0412_01
*****************Start to render snap images for scene0412_01*****************
Snap module: 23 out of 24 images rendered*****************Start to Build Lookup Dict for scene0412_01*****************
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 191.09it/s]
 44%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                  | 132/303 [2:04:22<2:28:03, 51.95s/it]Processing scene scene0414_00
*****************Start to render snap images for scene0414_00*****************
Snap module: 23 out of 24 images rendered*****************Start to Build Lookup Dict for scene0414_00*****************
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 188.94it/s]
 44%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                 | 133/303 [2:05:23<2:34:28, 54.52s/it]Processing scene scene0423_00
 44%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                 | 133/303 [2:05:24<2:40:17, 56.57s/it]
Traceback (most recent call last):
  File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 289, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, snap_folder=args.snap_folder, save_folder=args.save_folder, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 49, in __init__
    self.OV_instance_seg()
  File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 86, in OV_instance_seg
    self.snap.scene_image_rendering(scene_path, scene, mode=["global", "wide", "corner"])
  File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/snap.py", line 262, in scene_image_rendering
    mesh, _ = self.get_rid_of_lip(mesh, scan_pc_raw, self.remove_lip)
  File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/snap.py", line 97, in get_rid_of_lip
    cropped_mesh = pytorch3d.structures.Meshes(
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/meshes.py", line 433, in __init__
    shape_ok = self.textures.check_shapes(self._N, self._V, self._F)
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/renderer/mesh/textures.py", line 1580, in check_shapes
    return self.verts_features_padded().shape[:-1] == (batch_size, max_num_verts)
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/renderer/mesh/textures.py", line 1428, in verts_features_padded
    self._verts_features_padded = list_to_padded(
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/utils.py", line 63, in list_to_padded
    pad_dims = [
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/utils.py", line 64, in <listcomp>
    max(y.shape[dim] for y in x if len(y) > 0) for dim in range(x[0].ndim)
ValueError: max() arg is an empty sequence`

I’m really sorry for taking up so much of your time before. I should be able to resolve this issue on my own, but if you have any suggestions, please feel free to share them.

Thank you so much for your recent advice and assistance. It has been incredibly helpful and has made this work much better.

Best regards,
Jiacheng

**Comment by JiachengDeng** [comment] 2024-09-08 14:37
> Hello Zhening,
> 
> First of all, I apologize for the delayed response and keeping you waiting. I have successfully started training the scannet OVIS with the newer release, but over the past few days, I’ve been working hard to fix some other minor bugs I encountered. For example, I’m currently addressing the following issue:
> 
> `Processing scene scene0412_01 *****************Start to render snap images for scene0412_01***************** Snap module: 23 out of 24 images rendered*****************Start to Build Lookup Dict for scene0412_01***************** 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 191.09it/s] 44%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 132/303 [2:04:22<2:28:03, 51.95s/it]Processing scene scene0414_00 *****************Start to render snap images for scene0414_00***************** Snap module: 23 out of 24 images rendered*****************Start to Build Lookup Dict for scene0414_00***************** 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 188.94it/s] 44%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 133/303 [2:05:23<2:34:28, 54.52s/it]Processing scene scene0423_00 44%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 133/303 [2:05:24<2:40:17, 56.57s/it] Traceback (most recent call last): File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 289, in <module> openins3d = OpenIns3D(dataset_name.lower(), dataset_path, snap_folder=args.snap_folder, save_folder=args.save_folder, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis) File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 49, in __init__ self.OV_instance_seg() File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/main.py", line 86, in OV_instance_seg self.snap.scene_image_rendering(scene_path, scene, mode=["global", "wide", "corner"]) File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/snap.py", line 262, in scene_image_rendering mesh, _ = self.get_rid_of_lip(mesh, scan_pc_raw, self.remove_lip) File "/ssd/djc/open-vocabulary/OV-3DIns/openins3d/snap.py", line 97, in get_rid_of_lip cropped_mesh = pytorch3d.structures.Meshes( File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/meshes.py", line 433, in __init__ shape_ok = self.textures.check_shapes(self._N, self._V, self._F) File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/renderer/mesh/textures.py", line 1580, in check_shapes return self.verts_features_padded().shape[:-1] == (batch_size, max_num_verts) File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/renderer/mesh/textures.py", line 1428, in verts_features_padded self._verts_features_padded = list_to_padded( File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/utils.py", line 63, in list_to_padded pad_dims = [ File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/structures/utils.py", line 64, in <listcomp> max(y.shape[dim] for y in x if len(y) > 0) for dim in range(x[0].ndim) ValueError: max() arg is an empty sequence`
> 
> I’m really sorry for taking up so much of your time before. I should be able to resolve this issue on my own, but if you have any suggestions, please feel free to share them.
> 
> Thank you so much for your recent advice and assistance. It has been incredibly helpful and has made this work much better.
> 
> Best regards, Jiacheng

I found that the issue occurs when processing scene0423_00, where line 82 in snap.py (`idx = a[:, 2] <= z_max - remove_lip`) returns all False, and ultimately in line 87 (`a = a[idx]`), the a data becomes `tensor([], device='cuda:0', size=(0, 3))`. This eventually leads to the error: '`ValueError: max() arg is an empty sequence`'.

**Comment by ZheningHuang** [comment] 2024-09-08 19:28
Hi Jiacheng,

I really appreciate your thorough testing of the code and for reporting the issues. No worries at all. Please don't hesitate to let us know if you encounter any other problems—discussion is always welcome.

Regarding the bugs you've identified, you're absolutely right—it is indeed a bug, as I just confirmed through testing.

When I was testing with ScanNet, I was using a smaller value for the `remove_lip` parameter, which hided the bug you pointed out. As you might imagine, you can simply add an `if` statement to work around this issue, like so:

```python
def get_rid_of_lip(self, mesh, scan_pc, remove_lip):
    """
    Given a mesh file in PyTorch3D, remove the lip with a predefined height, and return a mesh file in PyTorch3D
    """
    verts = mesh.verts_packed()
    faces = mesh.faces_packed()
    texture_tensor = mesh.textures.verts_features_packed()
    z_max = scan_pc[:, 2].max()

    if remove_lip >= z_max:
        remove_lip = 0

    idx = verts[:, 2] <= z_max - remove_lip
```

As always, this bug has been fixed and pushed. Thanks again for your valuable contribution! Please feel free to reach out with any future issues

Zhening

**Closed as completed** 2024-09-10 12:51 UTC
